// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEty1MSZq3lAGtMzqQmBwvneKvk0td7c0',
    appId: '1:252255111361:web:28fa4a4a9031384044ac40',
    messagingSenderId: '252255111361',
    projectId: 'testing-e0433',
    authDomain: 'testing-e0433.firebaseapp.com',
    storageBucket: 'testing-e0433.appspot.com',
    measurementId: 'G-N3BQREHCP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1sLvWI1ex6r65A3N1wJ4puPTPOrXSV3M',
    appId: '1:252255111361:android:1eab5819a06fa38d44ac40',
    messagingSenderId: '252255111361',
    projectId: 'testing-e0433',
    storageBucket: 'testing-e0433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGGyUFZ6pn3obPaLhe1rxJpv4xcUr7RBE',
    appId: '1:252255111361:ios:bb31db5e345437e944ac40',
    messagingSenderId: '252255111361',
    projectId: 'testing-e0433',
    storageBucket: 'testing-e0433.appspot.com',
    iosBundleId: 'com.example.flutterApplicationPrak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGGyUFZ6pn3obPaLhe1rxJpv4xcUr7RBE',
    appId: '1:252255111361:ios:bb31db5e345437e944ac40',
    messagingSenderId: '252255111361',
    projectId: 'testing-e0433',
    storageBucket: 'testing-e0433.appspot.com',
    iosBundleId: 'com.example.flutterApplicationPrak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEty1MSZq3lAGtMzqQmBwvneKvk0td7c0',
    appId: '1:252255111361:web:20e7711ab648aefe44ac40',
    messagingSenderId: '252255111361',
    projectId: 'testing-e0433',
    authDomain: 'testing-e0433.firebaseapp.com',
    storageBucket: 'testing-e0433.appspot.com',
    measurementId: 'G-ZCZWXD9QJD',
  );
}
